<?php
/*session_start();

// Check if the user is logged in and has the 'admin' role
if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'admin') {
    header("Location: login.html");
    exit;
}*/
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Maintenance Task Management Page</title>
    <link rel="stylesheet" href="styles.css">
</head>

    <body>
    <!--header-->
    <header>
            <div class="logo">
                <table>
                    <tr>
                        <td><img src="src/logo_miniktm.png" alt="KTMB Logo"></td>
                        <td><h3>KERETAPI TANAH MELAYU BERHAD</h3></td>
                        <td><h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Owner - OOI POH QIN</h3></td>
                        <td><h3>&nbsp;&nbsp;&nbsp;Welcome, <?php //echo $_SESSION['fullname']; ?>!</h3></td>
                    </tr>
                </table>
            </div>
        </header>
        
        <!-- Navigation Bar -->
        <nav class="navbar2">
            <ul class="trytgok">
                <li><a href="index.html">Dashboard</a></li>
                <li><a href="maintenance.html">Maintenance Task Management</a></li>
                <li><a href="UserManagementPage.html">User Management</a></li>
                <li><a href="#">Reported Issue</a></li>
                <li><a href="aboutUs_staff.php" class="active">About Us</a></li>
            </ul>
        
            <!-- User Icon -->
            <div class="user-icon2">
                <img src="src/user icon.png" alt="User Icon" id="userIcon">
                <div class="dropdown-menu">
                    <a href="#">User Profile</a>
                    <a href="#">Log Out</a>
                </div>
            </div>
        </nav>       

    <!-- Create Maintenance Task Table -->
    <main>
        <section class="create-task">
            <h2>Create Maintenance Task</h2>
            <form action="create_tasks.php" method="POST">
            <table>
                <tr>
                    <th>Task ID</th>
                    <th>Task Name</th>
                    <th>Priority Level</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                </tr>
                <tr>
                    <td>Autogenerated</td>
                    <td><input type="text" name="task_name" placeholder="Input Task Name" required></td>
                    <td>
                        <select name="priority_level" required>
                            <option value="High">High</option>
                            <option value="Medium">Medium</option>
                            <option value="Low">Low</option>
                        </select>
                 </td>
                    <td><input type="date" name="start_date" required></td>
                    <td><input type="date" name="end_date" required></td>
                </tr>
            </table>
            <button type="submit" class="add-task-button">Add Task</button>
            </form>
        </section>

        <!-- Maintenance Task Table -->
        <section class="task-table">
            <h2>Maintenance Task Table</h2>
            <table>
                <thead>
                    <tr>
                        <th>Task ID</th>
                        <th>Task Name</th>
                        <th>Priority Level</th>
                        <th>Start Date</th>
                        <th>End Date</th>
                    </tr>
                </thead>
                <tbody>
                    <?php include 'display_tasks.php'; ?>
                </tbody>
            </table>
        </section>
    </main>

    <script>
        // JavaScript for Dropdown Menu
        const userIcon = document.getElementById('userIcon');
        const dropdownMenu = document.querySelector('.dropdown-menu');

        userIcon.addEventListener('click', () => {
            dropdownMenu.classList.toggle('show');
        });

        // Close dropdown when clicking outside
        window.addEventListener('click', (e) => {
            if (!userIcon.contains(e.target) && !dropdownMenu.contains(e.target)) {
                dropdownMenu.classList.remove('show');
            }
        });
    </script>
    
</body>
</html>
